import { Building, Rocket, Shield } from 'lucide-react';

export const industryPricing = [
    {
        name: 'Standard',
        priceMonthly: '99',
        priceYearly: '999',
        currency: '$',
        period: 'per month',
        description: 'Ideal for small to medium-sized businesses in the industry.',
        icon: Building,
        features: ['Up to 20 AI Agents', 'Industry-specific knowledge base', 'Priority support', 'Advanced analytics'],
        buttonText: 'Get Started',
        popular: false,
        gradient: 'from-gray-500 to-gray-600',
    },
    {
        name: 'Advanced',
        priceMonthly: '249',
        priceYearly: '2499',
        currency: '$',
        period: 'per month',
        description: 'For businesses requiring more advanced features and support.',
        icon: Rocket,
        features: [
            'Everything in Standard',
            'Up to 50 AI Agents',
            'Custom integrations',
            'Dedicated account manager',
            '24/7 support',
        ],
        buttonText: 'Start Advanced Trial',
        popular: true,
        gradient: 'from-purple-500 to-blue-500',
    },
    {
        name: 'Enterprise',
        priceMonthly: 'Custom',
        priceYearly: 'Custom',
        currency: '',
        period: 'contact us',
        description: 'Tailored solutions for large-scale industry applications.',
        icon: Shield,
        features: [
            'Everything in Advanced',
            'Unlimited AI Agents',
            'On-premise deployment',
            'Custom SLA',
            'White-glove onboarding',
        ],
        buttonText: 'Contact Sales',
        popular: false,
        gradient: 'from-emerald-500 to-cyan-500',
    },
];
