import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cool Macaly App",
  description: "Generated by Macaly",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://promptbook.studio/api/embed/miniapp.js?id=5e408aff-6fc5-42f1-9db9-fa8601c626ae"
          strategy="afterInteractive"
          onLoad={() => {
            // @ts-ignore
            activateEmbeddedChatbot({
              "theme": "DARK",
              "position": "BOTTOM_RIGHT",
              "isTestingMode": false
            });
          }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
