import { createBrowserClient } from '@supabase/ssr';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const isSupabaseConfigured = !!(supabaseUrl && supabaseKey);

if (!isSupabaseConfigured) {
    console.warn(
        '⚠️ Supabase not configured - API routes will be disabled. Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to enable.',
    );
}

export const supabase: SupabaseClient | null = isSupabaseConfigured ? createClient(supabaseUrl!, supabaseKey!) : null;

if (supabase) {
    //* not await */ testSupabaseConnection(supabase);
}

export function createSupabaseClient(): SupabaseClient | null {
    if (!isSupabaseConfigured) return null;
    const client = createClient(supabaseUrl!, supabaseKey!);
    //* not await */ testSupabaseConnection(client);
    return client;
}

export function getSupabaseForBrowser(): SupabaseClient | null {
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) return null;
    const client = createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
    //* not await */ testSupabaseConnection(client);
    return client;
}

export async function testSupabaseConnection(client: ReturnType<typeof createSupabaseClient>) {
    console.info('⚡ Testing Supabase connection...');

    /*
    const result = await client.rpc('list_tables');

    if (result.error) {
        console.error('⚡ Error connecting to Supabase:', result.error);
        return;
    }

    console.groupCollapsed('⚡ Supabase connection successful');
    console.log('Tables:', result.data);
    console.groupEnd();
    */
}

/*
CREATE TABLE public."Contact" (
    "id" integer generated by default as identity primary key,
    "createdAt" timestamp with time zone not null default now(),
    "fullname" text null,
    "email" text null,
    "phone" text null,
    "userNote" text null,
    "isContacted" boolean null,
    "ourNote" text null,
    "userAgent" text null,
    "ipAddress" inet null,
    "referrer" text null,
    "appName" text null,
    "placeName" text null,
    "url" text null
) TABLESPACE pg_default;
*/
