import { createBrowserClient } from '@supabase/ssr';
import { createClient, SupabaseClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

const isSupabaseConfigured = !!(supabaseUrl && supabaseKey);

if (!isSupabaseConfigured) {
    console.warn(
        '⚠️ Supabase not configured - API routes will be disabled. Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY to enable.',
    );
}

export const supabase: SupabaseClient | null = isSupabaseConfigured ? createClient(supabaseUrl!, supabaseKey!) : null;

if (supabase) {
    //* not await */ testSupabaseConnection(supabase);
}

export function createSupabaseClient(): SupabaseClient | null {
    if (!isSupabaseConfigured) return null;
    const client = createClient(supabaseUrl!, supabaseKey!);
    //* not await */ testSupabaseConnection(client);
    return client;
}

/**
 * Talk to the database as the service role, or `null` when this server does not hold the service role key
 *
 * Note: The service role key is the only key which reaches a table protected by row level security, like `Contact`.
 *       It is not a `NEXT_PUBLIC_` variable, so it is never part of the browser bundle and the browser can therefore
 *       never reach such a table.
 *
 * Note: The public anonymous key is deliberately not used as a fallback here. Under row level security it would not
 *       fail, it would quietly answer that there is nothing to see, which is far harder to notice than a missing key.
 */
export function createSupabaseServiceRoleClient(): SupabaseClient | null {
    const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!supabaseUrl || !supabaseServiceRoleKey) {
        return null;
    }

    return createClient(supabaseUrl, supabaseServiceRoleKey, {
        // Note: A server talks for everybody at once, so it must never carry over a session from one request to another
        auth: { persistSession: false, autoRefreshToken: false },
    });
}

export function getSupabaseForBrowser(): SupabaseClient | null {
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) return null;
    const client = createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
    //* not await */ testSupabaseConnection(client);
    return client;
}

export async function testSupabaseConnection(client: ReturnType<typeof createSupabaseClient>) {
    console.info('⚡ Testing Supabase connection...');

    /*
    const result = await client.rpc('list_tables');

    if (result.error) {
        console.error('⚡ Error connecting to Supabase:', result.error);
        return;
    }

    console.groupCollapsed('⚡ Supabase connection successful');
    console.log('Tables:', result.data);
    console.groupEnd();
    */
}

/*
Note: The tables of the online workshop are written down in `lib/workshop/workshop-tables.sql`
*/

/*
Note: The `Contact` table below is closed by row level security, which is written down in
      `lib/contacts/contact-table-rls.sql`. It is reachable only with the service role key, so every contact is written
      and read through `/api/waitlist` and `/api/contacts` instead of directly from the browser.
*/

/*
CREATE TABLE public."Contact" (
    "id" integer generated by default as identity primary key,
    "createdAt" timestamp with time zone not null default now(),
    "fullname" text null,
    "email" text null,
    "phone" text null,
    "userNote" text null,
    "isContacted" boolean null,
    "ourNote" text null,
    "userAgent" text null,
    "ipAddress" inet null,
    "referrer" text null,
    "appName" text null,
    "placeName" text null,
    "url" text null
) TABLESPACE pg_default;
*/
