export const defaultPricing = [
    {
        name: 'Free',
        price: '$0',
        period: 'forever',
        description: 'Perfect for getting started with Promptbook',
        features: ['Create 1 AI Agent', 'Basic Knowledge and Rules', 'Community support', 'Open source access'],
        buttonText: 'Get Started',
        popular: false,
        gradient: 'from-gray-500 to-gray-600',
    },
    {
        name: 'Pro',
        price: '$49',
        period: 'per month',
        description: 'For businesses building custom AI solutions',
        features: [
            'Everything in Free',
            'Up to 10 AI Agents',
            'Advanced Knowledge and Rules',
            'Action Commitments',
            'Priority support',
            'Advanced analytics',
        ],
        buttonText: 'Start Pro Trial',
        popular: true,
        gradient: 'from-purple-500 to-blue-500',
    },
    {
        name: 'Enterprise',
        price: 'Custom',
        period: 'contact us',
        description: 'Custom solutions for large organizations',
        features: [
            'Everything in Pro',
            'Unlimited AI Agents',
            'Custom integrations',
            'Dedicated support',
            'On-premise deployment',
            'SLA guarantees',
            'Team management',
        ],
        buttonText: 'Contact Sales',
        popular: false,
        gradient: 'from-emerald-500 to-cyan-500',
    },
];

export const industryPricing = [
    {
        name: 'Standard',
        price: '$99',
        period: 'per month',
        description: 'Ideal for small to medium-sized businesses in the industry.',
        features: [
            'Up to 20 AI Agents',
            'Industry-specific knowledge base',
            'Priority support',
            'Advanced analytics',
        ],
        buttonText: 'Get Started',
        popular: false,
        gradient: 'from-gray-500 to-gray-600',
    },
    {
        name: 'Advanced',
        price: '$249',
        period: 'per month',
        description: 'For businesses requiring more advanced features and support.',
        features: [
            'Everything in Standard',
            'Up to 50 AI Agents',
            'Custom integrations',
            'Dedicated account manager',
            '24/7 support',
        ],
        buttonText: 'Start Advanced Trial',
        popular: true,
        gradient: 'from-purple-500 to-blue-500',
    },
    {
        name: 'Enterprise',
        price: 'Custom',
        period: 'contact us',
        description: 'Tailored solutions for large-scale industry applications.',
        features: [
            'Everything in Advanced',
            'Unlimited AI Agents',
            'On-premise deployment',
            'Custom SLA',
            'White-glove onboarding',
        ],
        buttonText: 'Contact Sales',
        popular: false,
        gradient: 'from-emerald-500 to-cyan-500',
    },
];
