export const defaultPricing = [
    {
        name: 'Free',
        priceMonthly: '0',
        priceYearly: '0',
        currency: '$',
        period: 'forever',
        description: 'Perfect for getting started with Promptbook',
        features: ['Create 1 AI Agent', 'Basic Knowledge and Rules', 'Community support', 'Open source access'],
        buttonText: 'Get Started',
        popular: false,
        gradient: 'from-gray-500 to-gray-600',
    },
    {
        name: 'Pro',
        priceMonthly: '49',
        priceYearly: '499',
        currency: '$',
        period: 'per month',
        description: 'For businesses building custom AI solutions',
        features: [
            'Everything in Free',
            'Up to 10 AI Agents',
            'Advanced Knowledge and Rules',
            'Action Commitments',
            'Priority support',
            'Advanced analytics',
        ],
        buttonText: 'Start Pro Trial',
        popular: true,
        gradient: 'from-purple-500 to-blue-500',
    },
    {
        name: 'Enterprise',
        priceMonthly: 'Custom',
        priceYearly: 'Custom',
        currency: '',
        period: 'contact us',
        description: 'Custom solutions for large organizations',
        features: [
            'Everything in Pro',
            'Unlimited AI Agents',
            'Custom integrations',
            'Dedicated support',
            'On-premise deployment',
            'SLA guarantees',
            'Team management',
        ],
        buttonText: 'Contact Sales',
        popular: false,
        gradient: 'from-emerald-500 to-cyan-500',
    },
];
