-- Tables behind the participant page of an online workshop
--
-- Note: Run this once in the SQL editor of the Supabase project. Until it is run, every workshop endpoint answers
--       "the workshop tables are missing" and the participant page falls back to the date from the landing page
--       configuration.
--
-- Note: The site talks to the database with the anonymous key and decides itself who may write, so the row level
--       security stays off for the tables below. The `Contact` table is the exception, it holds personal data of the
--       leads and is closed by `lib/contacts/contact-table-rls.sql`.

CREATE TABLE IF NOT EXISTS public."WorkshopSettings" (
    "workshopId" text PRIMARY KEY,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "title" text NOT NULL DEFAULT '',
    "startsAt" timestamp with time zone NOT NULL,
    "youtubeVideoId" text NULL,
    "isStreamLive" boolean NOT NULL DEFAULT false,
    "streamNote" text NULL,
    "isChatEnabled" boolean NOT NULL DEFAULT true
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."WorkshopContentBlock" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workshopId" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "title" text NOT NULL DEFAULT '',
    "contentMarkdown" text NOT NULL DEFAULT '',
    -- Note: `null` means the block is still a draft which no participant sees
    "unlockedAt" timestamp with time zone NULL,
    "sortOrder" integer NOT NULL DEFAULT 0
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "WorkshopContentBlock_workshopId_unlockedAt_idx"
    ON public."WorkshopContentBlock" ("workshopId", "unlockedAt");

CREATE TABLE IF NOT EXISTS public."WorkshopChatMessage" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workshopId" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "participantName" text NOT NULL,
    "participantId" text NULL,
    "messageText" text NOT NULL,
    "isHidden" boolean NOT NULL DEFAULT false
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "WorkshopChatMessage_workshopId_createdAt_idx"
    ON public."WorkshopChatMessage" ("workshopId", "createdAt");

CREATE TABLE IF NOT EXISTS public."WorkshopReaction" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "workshopId" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "participantId" text NULL,
    "reactionEmoji" text NOT NULL
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "WorkshopReaction_workshopId_createdAt_idx"
    ON public."WorkshopReaction" ("workshopId", "createdAt");
